rm(list=ls())
EPI_data <- read.csv(file.choose(),header = TRUE,skip = 1)
dim(EPI_data)
attach(EPI_data)
fix(EPI_data)
plot(ecdf(EPI),do.points = FALSE,verticals = TRUE)
plot(ecdf(EPI),do.points = TRUE,verticals = TRUE)
par(pty='s') #pty defines area. s is square, m is max
qqnorm(EPI_data$EPI)
qqline(EPI_data$EPI)
x <- seq(30,95,1)
x2 <-seq(30,95,2)
qqplot(qt(ppoints(250),df=5),x,xlab='Q-Q plot for tdsn')
qqline(x)


#Exercise 1
rf <- is.na(DALY)
E <- DALY[!rf]
summary(DALY)
fivenum(EPI,na.rm = TRUE)
stem(DALY)
hist(DALY)
hist(DALY,seq(0,92,1),pro=TRUE)
lines(density(DALY,na.rm=TRUE,bw=1))
rug(DALY)
plot(ecdf(DALY),do.points=FALSE,vertical=TRUE)
par(pty='s')
qqnorm(DALY)
qqline(DALY)
x<-seq(0,92,1)
qqplot(qt(ppoints(250),df=5),x,xlab='Q-Q plot for tdsn')
qqline(x)

boxplot(EPI_data$EPI,EPI_data$DALY)

multivariate <- read.csv(choose.files(),header = TRUE)
attach(multivariate)
mm <- lm(Homeowners~Immigrant)
mm
summary(mm)$coef
plot(Homeowners~Immigrant)
abline(mm)
abline(mm,col=2,lwd=3)
newImmigrantdata <- data.frame(Immigrant=c(0,20))
mm %>% predict(newImmigrantdata)

plot(mtcars$wt,mtcars$mpg)
library(ggplot2)
qplot(mtcars$wt,mtcars$mpg)
qplot(wt,mpg,data = mtcars)
ggplot(mtcars,aes(x=wt,y=mpg))+geom_point()
plot(pressure$temperature,pressure$pressure,type = "l")
points(pressure$temperature,pressure$pressure)
lines(pressure$temperature,pressure$pressure/2,col="red")
points(pressure$temperature,pressure$pressure/2,col="blue")
library(ggplot2)
qplot(pressure$temperature,pressure$pressure,geom = "line")
qplot(temperature,pressure,data=pressure,geom = "line")
ggplot(pressure,aes(x=temperature,y=pressure))+geom_line()+geom_point()

barplot(BOD$demand,names.arg = BOD$Time)
table(mtcars$cyl)
barplot(table(mtcars$cyl))
qplot(mtcars$cyl)
qplot(factor(mtcars$cyl))
qplot(factor(cyl),data=mtcars)
ggplot(mtcars,aes(x=factor(cyl)))+geom_bar()

plot(ToorhGrowth$supp,ToothGrowth$len)
